"""Semantic description of a locally executed Python/Jupyter inspection."""
import hashlib
import json
from rdflib import RDF, RDFS, OWL, Literal, URIRef
from workflow_sources import ARTIFACT_REVISION, artifact_source

TITLE = 'Read saved results with Python, inspect the data in a notebook, and compare the ecosystem trajectories.'


def extend(c):
    add, edge, uri, lit = (c[k] for k in ('add', 'edge', 'uri', 'lit'))
    g, SD, PROV, DCT, M4I, OBO, SCHEMA = (c[k] for k in ('g', 'SD', 'PROV', 'DCT', 'M4I', 'OBO', 'SCHEMA'))
    manifest = json.loads((c['OUT']/'data/python-inspection-manifest.json').read_text())
    report = json.loads((c['OUT']/'data/python-inspection.json').read_text())
    assert manifest['revision'] == c['REV']
    for path, digest in manifest['sources'].items():
        assert hashlib.sha256(c['read'](path, True)).hexdigest() == digest
    for path, digest in manifest['outputs'].items():
        assert hashlib.sha256((c['OUT']/path).read_bytes()).hexdigest() == digest
    g.add((SD.specifiesOutput, RDF.type, OWL.ObjectProperty))
    g.add((SD.specifiesOutput, RDFS.label, Literal('specifies output')))
    g.add((SD.specifiesOutput, RDFS.comment, Literal(
        'An executable source section specifies writing an artifact. This is a source-code relationship; observed generation is recorded separately with prov:generated on the executed activity.')))

    notebook = 'notebook/inspect-results'
    script = 'script/inspect-results'
    activity = 'processing/inspect-results-python'
    table = 'dataset/python-state-trajectories'
    summary = 'dataset/python-inspection-summary'
    figure = 'visualization/python-inspection'
    reader = 'file/scripts/vensim_csv.py'
    inputs = ['file/results/runs/case1_external.csv', 'file/results/runs/case2_external.csv']
    source_links = [c['src']('scripts/vensim_csv.py'), *[c['src'](p) for p in manifest['sources'] if p.endswith('.csv')]]

    def artifact(key, label, kind, definition, path, types):
        add(key, label, kind, definition, types, [artifact_source(path)], status='Generated locally',
            revision=ARTIFACT_REVISION, repositoryPath='docs/semantic/' + path,
            sha256=manifest['outputs'][path])
        lit(key, SD.sha256, manifest['outputs'][path])
        lit(key, SD.path, 'docs/semantic/' + path)
        lit(key, SD.revision, ARTIFACT_REVISION)

    artifact(notebook, 'inspect_results.ipynb', 'Notebook',
             'Executed Jupyter notebook with five numbered sections: verify source files, read data, build a pandas table, inspect descriptive statistics, and compare trajectories. Its saved outputs are included in the repository. No simulation is run.',
             'notebooks/inspect_results.ipynb', [PROV.Plan, SCHEMA.CreativeWork])
    artifact(script, 'inspect_results.py', 'Script',
             'Readable Python source generated from the notebook, retaining its headings and five code cells. The only code difference is that the Jupyter inline-plot magic is a comment. Section links target exact source lines in this representation.',
             'notebooks/inspect_results.py', [PROV.Plan, SCHEMA.SoftwareSourceCode])
    artifact(table, 'State trajectories in pandas', 'Dataset',
             'Three simulated states from both cases, exported by notebook cell 3: 2,002 rows and three quantity columns, indexed by case and year. The historical reference stays on its separate 21-point time axis.',
             'data/python-state-trajectories.csv', [PROV.Entity])
    artifact(summary, 'Peaks and final values', 'Dataset',
             'Six rows exported by notebook cell 4: three state variables in each case, with units, sample count, minimum, maximum, sampled peak year and final value. These descriptive comparisons do not isolate a causal effect.',
             'data/python-inspection-summary.csv', [PROV.Entity])
    artifact(figure, 'Compare cases in Python', 'Visualization',
             'Three-panel SVG generated by notebook cell 5, comparing both committed cases. The historical reference keeps its 21-point time axis; no resampling or interpolation is performed.',
             'data/python-inspection.svg', [PROV.Entity])
    for key, caption in [(notebook, 'Jupyter notebook · executed'), (script, 'Python source · notebook cells'),
                         (table, 'pandas table · CSV'), (summary, 'Descriptive statistics · CSV'),
                         (figure, 'Comparison figure · SVG')]:
        c['entities'][key]['displayType'] = caption
    add(activity, 'Inspect data with Python', 'Run',
        'Executed notebook activity using the repository CSV reader. It preserves time axes and units, assembles compatible series in pandas, computes statistics and plots comparisons. It uses an ordinary Python kernel; no PySD simulation is executed.',
        [M4I.ProcessingStep, PROV.Activity], source_links, navigation='explore', status='Executed locally',
        displayType='Python inspection · executed')
    selected_edges = []
    def rel(a, p, b, label, show=True):
        edge(a, p, b, label, status='Executed locally')
        if show:
            selected_edges.append(c['edges'][-1])
    for item in inputs:
        rel(activity, OBO.RO_0002233, item, 'has input', False)
        rel(item, SD.inputTo, activity, 'read as input')
    rel(activity, PROV.used, reader, 'uses reader')
    rel(activity, PROV.used, notebook, 'executes notebook')
    rel(notebook, DCT.hasFormat, script, 'has Python source view', False)

    labels = ['Verify source files', 'Read units and time axes', 'Build the pandas table',
              'Inspect peaks and final values', 'Compare trajectories']
    definitions = [
        'Code cell 1 locates the repository, verifies SHA-256 hashes of the reader and both CSVs, imports dependencies and prepares the output folder.',
        'Code cell 2 calls read_dataset, inventories variables and units, and checks the independent 1,001-point and 21-point time axes.',
        'Code cell 3 verifies matching state axes, builds a pandas DataFrame for both cases and exports python-state-trajectories.csv.',
        'Code cell 4 computes sampled peaks, final values and other descriptive statistics, and exports the summary CSV and inspection report.',
        'Code cell 5 creates three comparison panels, plots the historical reference on its original axis and saves python-inspection.svg.',
    ]
    sections = []
    for info, label, definition in zip(manifest['sections'], labels, definitions):
        key = f'notebook-section/inspect-results/cell-{info["number"]}'
        source = artifact_source(info['previewPath'],
                                 label=f'Notebook cell {info["number"]} · rendered notebook')
        code_source = artifact_source('notebooks/inspect_results.py',
                                      f'L{info["pythonStartLine"]}-L{info["pythonEndLine"]}')
        add(key, label, 'Notebook section', definition, [PROV.Plan, SCHEMA.CreativeWork],
            [source, artifact_source('notebooks/inspect_results.ipynb'), code_source],
            status='Executed locally', displayType=f'Notebook cell {info["number"]} · rendered preview',
            sourceAction='open rendered notebook',
            revision=ARTIFACT_REVISION, notebookCell=info,
            details=[info['heading'], 'Opens the notebook section with its saved output. The excerpt links back to the complete executable notebook.'])
        lit(key, SD.selector, f'Notebook code cell {info["number"]}; id={info["cellId"]}; heading={info["heading"]}')
        rel(notebook, DCT.hasPart, key, f'cell {info["number"]}')
        rel(key, DCT.isPartOf, notebook, 'section of notebook', False)
        rel(script, DCT.hasPart, key, 'source for notebook cell', False)
        rel(activity, PROV.used, key, 'executes cell', False)
        sections.append(dict(id=key, label=label, url=source['url'], **info))
    rel(sections[1]['id'], DCT.references, reader, 'calls CSV reader', False)
    for index, output, label in [(2, table, 'specifies table'), (3, summary, 'specifies summary'), (4, figure, 'specifies figure')]:
        rel(sections[index]['id'], SD.specifiesOutput, output, label)
        rel(activity, PROV.generated, output, 'generates artifact', False)
        for item in inputs:
            rel(output, PROV.wasDerivedFrom, item, 'derived from', False)

    workflow = 'workflow/python-inspection'
    add(workflow, TITLE, 'Workflow',
        'Executed Python inspection of committed results, showing repository code, each notebook cell and the outputs specified by those cells. PySD is an optional upstream simulation route.',
        [SCHEMA.CreativeWork], source_links, navigation='explore', status='Review example')
    stages = [dict(label='Choose saved results', entity=inputs[0]),
              dict(label='Inspect with Python', entity=activity),
              dict(label='Use repository code', entity=notebook),
              dict(label='Follow notebook cells', entity=sections[0]['id']),
              dict(label='Inspect the outputs', entity=table)]
    sequence = URIRef(str(uri(workflow)) + '/sequence')
    g.add((uri(workflow), SD.artifactSequence, sequence)); g.add((sequence, RDF.type, RDF.Seq))
    for index, stage in enumerate(stages, 1):
        g.add((sequence, URIRef(str(RDF) + '_' + str(index)), uri(stage['entity'])))
        edge(workflow, DCT.hasPart, stage['entity'], 'includes workflow entity', status='Interpreted')
    return dict(id=workflow, slug='python-inspection', graphKey='diagram/python-inspection',
                title=TITLE, stages=stages, sections=sections, artifactRevision=ARTIFACT_REVISION,
                entities=list(dict.fromkeys(k for e in selected_edges for k in (e['source'], e['target']))),
                edges=selected_edges, manifest=manifest, report=report,
                summary='Follow Case 1 and Case 2 CSVs through the repository reader, five notebook cells, and their tables and comparison figure.',
                caveat='The notebook has been executed against saved results. This workflow does not run a new simulation.',
                actions=[dict(label='View notebook in repository', url=artifact_source('notebooks/inspect_results.ipynb')['url']),
                         dict(label='View Python source', url=artifact_source('notebooks/inspect_results.py')['url']),
                         dict(label='View comparison figure', url=artifact_source('data/python-inspection.svg')['url'])],
                note='Each cell opens a rendered notebook excerpt with its saved output and a link to the complete notebook. The 21 historical observations stay separate from the 1,001 simulated samples.',
                pythonSupport=dict(text='The repository also has a PySD runner that prepares the model and external inputs and writes tidy CSV, providing an upstream route for inspecting new Python runs.',
                                   source=c['source']('runners/pysd/run.py', 598)))
