# SPDX-FileCopyrightText: 2026 Vasiliy Seibert
# SPDX-License-Identifier: MIT
"""Author the HTML lecture and a complete map to the 52 reference topics."""
from pathlib import Path
from html import escape as E
import json

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'docs/slides'
REPO = 'https://github.com/FAIR-systemDynamics/fair-hunter-prey-simulation'
BLOB = REPO + '/blob/__REVISION__/'
SITE = 'https://fair-systemdynamics.github.io/fair-hunter-prey-simulation/'
RDA = 'https://doi.org/10.15497/RDA00068'
S = []

def p(text): return '<p>'+text+'</p>'
def ul(*items): return '<ul>'+''.join('<li>'+x+'</li>' for x in items)+'</ul>'
def code(text, label='Example'): return '<div class="artefact"><div class="file-head">'+E(label)+'</div><pre><code>'+E(text)+'</code></pre></div>'
def table(headers, rows): return '<table class="compare"><thead><tr>'+''.join('<th>'+x+'</th>' for x in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+str(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table>'
def cols(left,right): return '<div class="two-col"><div>'+left+'</div><div>'+right+'</div></div>'
def image(name,alt,caption=''): return '<figure><a class="screenshot-link" href="assets/evidence/'+name+'" target="_blank" rel="noopener" aria-label="Open full-size screenshot: '+E(alt)+'"><img src="assets/evidence/'+name+'" alt="'+E(alt)+'"></a><figcaption>'+caption+' <a href="assets/evidence/'+name+'" target="_blank" rel="noopener">Open full-size image ↗</a></figcaption></figure>'
def link(url,label): return '<a href="'+E(url)+'">'+label+'</a>'
def file(path,label=None): return link(BLOB+path,label or path)
def add(n,id,title,body,group='Opening',fair='',stage='specification',notes='',sources=(),kind='content'):
    S.append(dict(original=n,id=id,title=title,body=body,group=group,fair=fair,stage=stage,notes=notes,sources=list(sources),kind=kind))
def divider(n,id,title,group,fair,stage): add(n,id,title,p('Shared scientific specification. Different implementations. Evidence that travels with the research.'),group,fair,stage,kind='chapter-page')
def fa(n,id,title,body,**kw): add(n,id,title,body,'Findable & Accessible',**kw)
def inter(n,id,title,body,**kw): add(n,id,title,body,'Interoperable',**kw)
def reuse(n,id,title,body,**kw): add(n,id,title,body,'Reusable',**kw)

add(1,'title','FAIR research with proprietary simulation tools',p('One Kaibab model. Vensim and Stella Architect. Open artifacts for inspection and reuse.')+p('NFDI4Ing RDM Basics · Research Software · Vasiliy Seibert')+p('With implementations by Raphael Ginster, Matthias Papesch and Vasiliy Seibert'),kind='cover-page',notes='90-minute lecture. Model source: Deaton and MacDonald, System Dynamics Learning Guide (2025). Model-derived material is CC BY-NC-SA 4.0. Vendor applications remain proprietary.',sources=[REPO,'https://pressbooks.lib.jmu.edu/sdlearningguide/'])
add(2,'recap','Research data and research software',cols(ul('<strong>Motivation:</strong> FAIR principles, identifiers and credit.','<strong>Planning:</strong> a management plan in RDMO.','<strong>Metadata:</strong> shared meanings and documented relationships.'),p('Today we follow the software and artifacts that produce the data, including the dependencies needed to interpret and rerun them.')),sources=[RDA])
add(3,'agenda','Today’s route through the example',table(['Minutes','Activity'],[['0–10','Shared model, two tools, two cases'],['10–24','Findable and Accessible'],['24–34','Practical 1: discover and inspect metadata'],['34–47','Interoperable'],['47–59','Practical 2: inspect exports, then execute with PySD'],['59–73','Reusable'],['73–85','Practical 3: package an actual run'],['85–90','Checklist and discussion']]),notes='Optional appendix provides file-level demonstrations. Shorten appendix discussion, not the hands-on instructions, to stay within 90 minutes.')
add(4,'why-fair','What a future collaborator needs',cols(ul('Find the exact model and case.','Understand access and licensing.','Inspect the evidence without your desktop application.','Know what was executed and what was only documented.'),p('FAIR practices apply to the research artifacts around Vensim and Stella. They do not change the proprietary licenses of the applications.')),sources=[RDA])
add(5,'shared-specification','The scientific specification comes first',cols(p('The literature defines an ecosystem of <strong>deer, predators and forage</strong>. Equations, lookup functions, units and initial conditions describe the scientific problem.'),image('semantic-model.jpg','Existing semantic overview linking literature, equations and implementations','The existing semantic model connects the specification to both native implementations.')),notes='Tool-agnostic means shared scientific meaning. It does not imply identical serialization, software behavior or numerical trajectories.',sources=[SITE+'#overview','https://pressbooks.lib.jmu.edu/sdlearningguide/'])
add(None,'shared-use-cases','The same use cases, different tools',table(['Use case','Vensim implementation','Stella Architect implementation'],[['Define and edit','Equations and sketch in .mdl','Equations and views in .stmx'],['View and document','Native views; exported HTML/SVG','Native views; exported equations, PDF/SVG'],['Configure','External .cin, CSV and workbook','Parameter, lookup and historical CSVs'],['Execute','Native Vensim engine','Native Stella engine'],['Export and share','Source, documentation, result CSV','Source, documentation, result CSV']]),stage='implementation',notes='Comments and model documentation belong to the define/document workflow. Viewing exported diagrams does not require a vendor editor. Native authoring and execution use the respective vendor tools.',sources=[BLOB+'models/kaibab_ecosystem_model.mdl',BLOB+'examples/stella-source/models/kaibab_ecosystem_model.stmx'])
add(None,'artifacts-access','A source file, a result, or a bundle?',table(['Artifact','What it carries','Access boundary'],[['.mdl / .stmx','Editable model declarations; .stmx is XML/XMILE','Readable source, tool-specific semantics'],['CSV / HTML / SVG / PDF','Exported values or documentation','Open inspection in appropriate readers'],['.vpmx','Vensim packaged model','Vendor runtime; an export option, absent here'],['ZIP / .stmz','Stella bundled model and supporting files','Container only; an export option, absent here']]),stage='implementation',notes='Do not equate a ZIP archive with an interoperable model or reproducible run. Proprietary does not always mean paid access: vendor readers/players may offer free viewing or execution with restrictions.',sources=['https://vensim.com/vensim-applications/','https://ssl.iseesystems.com/resources/help/v4/Content/08-Reference/03-Menus/File_menu.htm'])
add(None,'two-cases','Case 2 changes four parameters',table(['Parameter','Case 1','Case 2'],[['Annual kills per predator','40','20'],['Carrying-capacity horizon','2 years','4 years'],['Desired consumption per deer','0.75 t/(deer·year)','0.5 t/(deer·year)'],['Predator removal fraction','0/year','0.2/year']])+p('The outcome is not an isolated predator-removal effect.</p><p class="case-files">Vensim: <strong>basic_parameters.cin</strong> + initial-stock workbook; add <strong>case2.cin</strong>.<br>Stella: <strong>…parameters_stella_scenario1.csv</strong> / <strong>…scenario2.csv</strong>.'),stage='configuration',sources=[BLOB+'models/config/scenarios/case2.cin',BLOB+'examples/stella-source/models/config/parameters/kaibab_ecosystem_parameters_stella_scenario2.csv'])
add(None,'open-workflows','Two open Python workflows',cols(p('<strong>Inspect saved exports</strong>')+ul('Read existing Vensim and Stella CSVs.','Use pandas and Matplotlib for tables and figures.','No simulation or proprietary application is executed.'),p('<strong>Run an implementation with PySD</strong>')+ul('Translate a copy of .mdl or .stmx.','Apply the existing numerical adapters.','Compare the new run with its own tool’s reference.')),stage='results',notes='CSV inspection is not performed by PySD. PySD is the independent simulation route. Both are useful interoperability examples, with different evidential claims.',sources=[BLOB+'docs/pysd_integration.md','https://pysd.readthedocs.io/en/latest/'])
divider(6,'findable-accessible','Findable & Accessible','Findable & Accessible','F · A','archive')
fa(7,'f1','F1: identify the research object',cols(p('Assign persistent identifiers to software. Distinguish components and versions when they represent different research objects.'),ul('Scientific specification and literature.','Vensim / Stella implementation files.','Case configuration and recorded execution.','A released software snapshot.')),fair='F1 · F1.1 · F1.2',stage='archive',sources=[RDA])
fa(8,'zenodo-webhook','A release can trigger a Zenodo deposit',table(['Step','Action','This repository'],[['Prepare','Review authors, licenses and release metadata','Prepared in .zenodo.json'],['Connect','Enable the repository in Zenodo GitHub settings','Not activated'],['Release','Publish an approved GitHub release','Not performed'],['Verify','Check ingestion and record the issued DOIs','Pending']]),fair='F1',stage='archive',notes='The awesome-sim reference has an active release webhook. This repository has no published DOI in this teaching addition. Do not create a release during the exercise.',sources=['https://help.zenodo.org/docs/github/enable-repository/',BLOB+'docs/fair/release.md'])
fa(9,'version-identifiers','Project identity and version identity',cols(p('<strong>Concept DOI</strong> identifies the project across deposited versions.')+p('<strong>Version DOI</strong> identifies a particular deposited snapshot.'),p('Before publication, record the full Git revision used for the run. A branch name moves; a commit identifies a specific source state.')+code('model implementation + case + source revision\n+ execution environment + generated output hashes','Execution identity')),fair='F1.1 · F1.2',stage='archive',notes='Existing v0.1-scaffold through v0.6-verification are teaching milestones, not evidence of Zenodo deposits. No DOI values are invented.',sources=[BLOB+'CHANGELOG.md'])
fa(10,'metadata-principles','F2–F4: metadata that points to evidence',ul('<strong>F2:</strong> describe the software richly enough to evaluate it.','<strong>F3:</strong> include the identifiers of the described objects.','<strong>F4:</strong> make metadata FAIR, searchable and indexable.','CFF and CodeMeta describe the repository. The semantic graph connects models, files, parameters and activities.'),fair='F2 · F3 · F4',sources=[RDA,BLOB+'CITATION.cff',BLOB+'codemeta.json'])
fa(11,'citation-codemeta','Citation metadata and software metadata',cols(code('cff-version: 1.2.0\ntype: software\nversion: 0.7.0.dev0\nauthors:\n  - family-names: Ginster\n    given-names: Raphael\n  - family-names: Papesch\n    given-names: Matthias\n  - family-names: Seibert\n    given-names: Vasiliy','CITATION.cff · excerpt'),code('"@type": "SoftwareSourceCode",\n"name": "fair-hunter-prey-simulation",\n"version": "0.7.0.dev0",\n"programmingLanguage": "Python",\n"runtimePlatform": [\n  "Python 3.12", "Python 3.13"\n]','codemeta.json · excerpt')),fair='F2 · F3',notes='Follow the file links for complete metadata, known ORCIDs and original-model references. Development version is not a published release. Do not guess missing personal identifiers.',sources=[BLOB+'CITATION.cff',BLOB+'codemeta.json'])
fa(12,'access-protocols','A1: retrieve the described artifact',cols(p('Standard protocols make files retrievable. The next question is whether a reader has the software and permissions needed to use them.'),ul('HTTPS: repository sources and documentation.','Git: history and exact revisions.','pip: the packaged Python execution route.','CSV: inspection without the native simulator.')),fair='A1 · A1.1',stage='implementation',sources=[RDA])
fa(13,'retrieve-install','Retrieve source or install a pinned snapshot',code('git clone '+REPO+'\n\npython -m pip install \\\n  "fair-hunter-prey[teaching] @ git+'+REPO+'@__REVISION__"','Terminal · Python 3.12 or 3.13')+p('The installed package contains both source implementations and their required inputs. It executes them through PySD.'),fair='A1 · A1.1',stage='implementation',sources=[BLOB+'pyproject.toml'])
fa(14,'authentication','A1.2: authentication where needed',ul('Read public sources and saved results without a GitHub account.','Sign in to a hosted Jupyter service to use your own workspace.','Use authenticated access for contributions and release administration.','Document native application access separately from access to research artifacts.'),fair='A1.2',sources=[RDA])
fa(15,'access-boundaries','Access is different for each use case',table(['Use case','Requirement'],[['Read equations / metadata','Text or web reader'],['Inspect exported tables / diagrams','CSV reader, browser or Python'],['Edit in a native graphical environment','Appropriate Vensim or Stella application'],['Run a native packaged model','Vensim Model Reader / isee Player; compatible models and terms'],['Run this supported model through Python','PySD plus this repository’s tested adapters']]),fair='A1.2',stage='implementation',notes='Proprietary does not always mean paid. Vensim Model Reader and isee Player are vendor-documented free runtime options with restricted authoring. Compatibility with this snapshot was not tested in either native application.',sources=['https://vensim.com/vensim-applications/','https://www.iseesystems.com/resources/help/v4/Content/Welcome.htm','https://pysd.readthedocs.io/en/latest/'])
fa(16,'persistent-metadata','A2: preserve the record of the research',cols(p('Metadata should remain accessible even if the software becomes unavailable.'),ul('Archive source snapshots and their attribution.','Preserve the scientific inputs and software environment.','State which artifacts require vendor software.','Keep identifier and archival claims tied to observed records.')),fair='A2',stage='archive',sources=[RDA])
fa(17,'archives','Zenodo and Software Heritage',table(['Service','Role','Evidence needed'],[['Zenodo','Deposit plus persistent metadata and DOI','Verified concept/version records'],['Software Heritage','Content-addressed source preservation','Verified archived object and SWHID'],['GitHub','Collaboration and current source history','Repository URL and full commit']])+p('For hunter–prey, external deposits and archive ingestion remain unverified. The release checklist records the next steps.'),fair='A2',stage='archive',sources=['https://archive.softwareheritage.org/',BLOB+'docs/fair/release.md'])
fa(18,'fa-recap','Findable and accessible evidence',ul('Identify which model, implementation, case and version you mean.','Describe them using machine-readable metadata and qualified links.','Make artifacts retrievable and explain the tools needed to use them.','Separate prepared publication steps from completed deposits.'),fair='F · A',stage='archive')
divider(19,'practical1','Practical 1: discover the model','Practical 1','F · A','specification')
add(20,'discover','Search, inspect, and follow the evidence',ul('Open '+link('https://software.nfdi4ing.de/','Betty Research Engine')+' and search for <strong>fair-hunter-prey-simulation</strong> or <strong>system dynamics</strong>.','Inspect the result source and available metadata. Export results if the service offers it.','If this repository is absent, record that indexing gap and use the '+link(REPO,'direct repository link')+'.','Read CFF/CodeMeta. Follow a model source, a case configuration, and the original literature.'),'Practical 1','F2 · F3 · F4','specification',notes='10 minutes. On 2026-10-09 the anonymous exact-name search returned no repositories and offered GitHub sign-in for broader results; authenticated enrichment was not tested. Service access or ranking can change. Do not promise a hit, citation count or ranking. Saved screenshots and direct artifact links support the exercise when the service is unavailable.',sources=['https://software.nfdi4ing.de/',REPO])
add(21,'discovery-reflection','What could you identify without asking the authors?',cols(ul('Which implementation and case?','Who receives credit?','What can you inspect immediately?'),p('A missing search result is evidence about discovery, not proof that a model is scientifically invalid. Metadata supports indexing; it does not guarantee a search position.')),'Practical 1','F · A','specification')
divider(22,'interoperable','Interoperable','Interoperable','I','results')
inter(23,'i1','I1: exchange data with explicit meaning',cols(p('Use domain-relevant formats and preserve what the values mean.'),ul('Shared quantities: deer, predators and forage.','Shared scenario meanings: Case 1 and Case 2.','Different CSV layouts require different readers.','Time axes, units and numerical methods remain part of the contract.')),fair='I1',stage='results',sources=[RDA,BLOB+'scripts/vensim_csv.py',BLOB+'scripts/stella_csv.py'])
inter(24,'formats','“CSV” is not a complete data specification',table(['Export','What the reader must preserve'],[['Vensim','Variable units and potentially several time axes'],['Stella trajectory','Horizontal values, time row and time unit'],['Stella final values','No time row; no invented trajectory'],['Stella inputs','Headerless parameters; lookup x/y rows; locale conventions']])+p('The existing readers make these differences explicit before pandas or Matplotlib receives the data.'),fair='I1',stage='results',sources=[BLOB+'scripts/vensim_csv.py',BLOB+'scripts/stella_csv.py'])
inter(25,'api-example','An explicit interface contract',cols(code('openapi: 3.1.0\ninfo:\n  title: Kaibab inspection API\n  version: 0.1.0\npaths:\n  /results/{implementation}/{case}:\n    get:\n      summary: Read saved results','Illustrative API sketch · no server deployed'),p('A future service would specify implementation, case, units, time-axis shape and errors. A final-values export cannot satisfy a promised trajectory response.')+p('The working interfaces here are the Python API, command line and documented CSV readers.')),fair='I1',stage='results',notes='Retains the original OpenAPI teaching topic. This is a design sketch, not an implemented web service.',sources=['https://spec.openapis.org/oas/v3.1.0'])
inter(26,'i2','I2: qualified references to other objects',ul('Cite the original literature and its license.','Link a scientific concept to its vocabulary identifier.','Connect an implementation variable to the concept it denotes.','Connect a parameter assignment to the file and field that supplies it.'),fair='I2',stage='configuration',notes='References to software dependencies are addressed explicitly under R2. The local semantic vocabulary remains a review draft.',sources=[RDA,SITE+'#overview'])
inter(27,'qualified-references','Trace a concept through both implementations',cols(code('Fraction Predators Killed per Year = 0.2','Vensim · case2.cin'),code('Fraction Predators Killed per Year,0.2','Stella · parameters_stella_scenario2.csv'))+p('One scientific concept: annual predator removal fraction (1/year). Case 1 uses 0; Case 2 uses 0.2.')+p('The execution record hashes the selected configuration and resulting stock data. Stella Case 2’s native evidence remains final values only.'),fair='I2',stage='configuration',notes='Follow the concept link to its semantic identifier and definition. The existing semantic assignment binds the Vensim changes file. The Stella binding shown here is a file-level trace to the unchanged CSV; this lecture does not add Stella assignment triples to the protected semantic graph. New PySD outputs carry provenance for either implementation. No claim is made that the parameter itself appears as a result column.',sources=[SITE+'#workflows/term%2Ffraction-predators-killed-per-year',BLOB+'models/config/scenarios/case2.cin',BLOB+'examples/stella-source/models/config/parameters/kaibab_ecosystem_parameters_stella_scenario2.csv'])
inter(28,'codemeta-references','Software metadata connects the artifact',ul(file('codemeta.json','CodeMeta')+' identifies the repository and development package.','Known author ORCIDs preserve attribution.','License URLs resolve to the applicable license definitions.','Dependency references point to maintained package records.','The semantic graph describes the scientific and file relationships in greater detail.'),fair='I2 · R2',stage='implementation',sources=[BLOB+'codemeta.json'])
inter(29,'controlled-vocabulary','One concept, separate declarations and assignments',cols(image('vocabulary.jpg','Vocabulary concept connected to a parameter and concept scheme'),ul('A SKOS concept carries a preferred label and definition.','The implementation variable denotes that concept.','Case 1 assigns 0; Case 2 assigns 0.2/year.','The graph describes the existing files. It does not control the simulator.')),fair='I2',stage='configuration',sources=[SITE+'#workflows/term%2Ffraction-predators-killed-per-year',BLOB+'docs/semantic/controlled-vocabulary.ttl'])
inter(30,'dependencies','Dependency constraints and tested environments',cols(code('dependencies = [\n  "pysd==3.14.3",\n  "pandas>=2.2,<3",\n  "matplotlib>=3.8,<4",\n  "openpyxl>=3.1,<4",\n]','pyproject.toml'),p('The package contract constrains supported versions. The teaching lock records a complete tested set.')+p('Changing a dependency may break parsing, translation or numerics. A permissive installation is not evidence of equivalent results.')),fair='R2',stage='execution',notes='Corrects the original placement: qualified references to other software belong to R2. Dependency ranges alone do not freeze transitive dependencies.',sources=[BLOB+'pyproject.toml'])
inter(31,'packaging','Installable without reorganizing the model',cols(ul('Package the unchanged runners and resource files.','Keep Vensim inputs in their original layout.','Keep the Stella snapshot in its own bundle.','Resolve resources from the installed package.'),code('from fair_hunter_prey import run_example\n\nrun = run_example(\n    "stella", "case2", "out/stella-case2"\n)\nprint(run["provenance"])','Python API')),fair='I1 · R2',stage='implementation',notes='Distribution name fair-hunter-prey, import name fair_hunter_prey. Wheel and Git installation are supported; no PyPI release is claimed.',sources=[BLOB+'pyproject.toml',BLOB+'setup.py'])
divider(32,'practical2','Practical 2: inspect, then execute','Practical 2','I · R','results')
add(33,'inspect-run','Open inspection before independent execution',code('from fair_hunter_prey import inspect_results, run_example\n\n# Saved native exports: no new simulation\nsaved = inspect_results("out/inspection")\n\n# Independent execution using the preserved adapters\nfor implementation in ("vensim", "stella"):\n    for case in ("case1", "case2"):\n        run_example(implementation, case,\n                    f"out/{implementation}-{case}")','Jupyter notebook · unique output folders')+p('Compare each PySD result with its own native reference. The Stella Case 2 reference supports a final-value comparison.'),'Practical 2','I1 · R2','execution',notes='12 minutes, including install. Use examples/fair/02_interoperability.ipynb. The kernel must use the installed teaching environment. Run folders are unique per notebook execution.',sources=[BLOB+'examples/fair/02_interoperability.ipynb'])
add(34,'interoperability-reflection','What made the exchange work?',ul('Shared scientific meanings, with explicit tool-specific file bindings.','Readers that preserve actual CSV structure and time axes.','Numerical adapters tested against native references.','Output provenance that names PySD as the execution engine.'),'Practical 2','I · R','results',notes='Ask participants which artifacts they could inspect without Vensim or Stella, and which information a bare CSV would have omitted.')
divider(35,'reusable','Reusable','Reusable','R','archive')
reuse(36,'r1','R1: describe, license, and trace',cols(ul('<strong>R1:</strong> relevant attributes for evaluating reuse.','<strong>R1.1:</strong> clear and accessible licenses.','<strong>R1.2:</strong> detailed provenance.'),p('For this model, a reusable result needs its implementation, case, input files, numerical method, environment and execution record.')),fair='R1 · R1.1 · R1.2',stage='archive',sources=[RDA])
reuse(37,'documentation','Documentation at each level',table(['Artifact','Question it answers'],[['README / teaching guide','How can I install and use it?'],['Model documentation','Which equations, units and assumptions?'],['Semantic site','How do concepts, files and activities connect?'],['Examples / notebooks','Which steps can I reproduce?'],['Changelog / contribution guide','What changed, and how can I contribute?']]),fair='R1',sources=[BLOB+'docs/fair/README.md',BLOB+'CONTRIBUTING.md'])
reuse(38,'licenses','The licenses travel with the artifacts',table(['Material','Existing license'],[['Original repository code and new adapters','MIT'],['General documentation','CC BY 4.0'],['Kaibab model and derived material','CC BY-NC-SA 4.0'],['Vendor applications','Separate proprietary terms'],['Service logos','Retained attribution and service-logo terms']])+p('REUSE maps licenses to paths. An open repository does not make every file public domain or remove model restrictions.'),fair='R1.1',stage='archive',sources=[BLOB+'LICENSE',BLOB+'REUSE.toml','https://spdx.org/licenses/'])
reuse(39,'provenance','A configuration is not an execution',cols(code('implementation: stella\ncase: case2\nengine: PySD\nmethod: rk2-heun\nsource_revision: <recorded commit>\ninputs: <file hashes>\noutputs: <file hashes>\nstarted: <observed UTC timestamp>','Recorded fields · values come from the run'),ul('The Git history records source changes.','The changelog explains notable changes.','A run record describes an observed execution.','The semantic site distinguishes reconstructed native provenance from observed inspection.')),fair='R1.2',stage='execution',sources=[BLOB+'CHANGELOG.md',SITE+'#workflows'])
reuse(40,'r2','R2: references to other software',ul('Record the Python and PySD versions.','Reference the actual readers and integration adapters.','Retain environment constraints and installed versions.','Record vendor software details where the source provides them.','Do not infer an application version or an execution event from a screenshot alone.'),fair='R2',stage='execution',sources=[RDA,BLOB+'docs/pysd_integration.md'])
reuse(41,'environments','Three levels of environment description',table(['Level','What it captures','Limit'],[['Dependency contract','Supported ranges in pyproject.toml','Not a frozen installation'],['Teaching lock + run record','Exact tested packages; observed Python/platform','Platform-specific packages still matter'],['Container recipe','OS and runtime layers, if actually built and recorded','Does not remove vendor licenses or guarantee future execution']])+p('This example supplies the first two. Containers remain a documented option; no container image is published.'),fair='R2',stage='execution',sources=[BLOB+'environments/teaching-py312.txt',BLOB+'environments/teaching-py313.txt'])
reuse(42,'r3','R3: community standards with evidence',ul('Standard Python packaging and an explicit public interface.','CFF and CodeMeta for software description.','REUSE and SPDX for license identification.','Tests against the existing scientific references.','Documented model formats and scenario meanings.'),fair='R3',sources=[RDA])
reuse(43,'ci','CI protects the scientific example',cols(ul('Run the original tests unchanged.','Check hashes of protected files.','Test both implementations and both cases.','Test installation outside the checkout.','Check the lecture and both Pages surfaces.'),code('python -m pytest tests -q\npython tools/fair/check_stella.py\ncffconvert --validate\nreuse lint\npython -m build','Review checks')),fair='R3',stage='execution',notes='Stella model tests run in a staged tree so its configuration CSVs cannot alter the existing Vensim directory inputs. Reference tolerances are preserved.',sources=[BLOB+'.github/workflows/fair.yml'])
reuse(44,'sustainability','A maintenance plan for the whole workflow',ul('Agree who reviews scientific changes and releases.','Record supported environments and deprecations.','Plan archival, identifier updates and end-of-support.','Retain attribution, licenses and old evidence.','Use '+link('https://rdmo.nfdi4ing.de/','RDMO')+' to agree responsibilities; this lecture does not assign them to collaborators.'),stage='archive',sources=[BLOB+'docs/fair/release.md'])
reuse(45,'reuse-recap','What would a missing artifact prevent?',table(['Missing artifact','Consequence'],[['Scenario configuration','The case is ambiguous'],['Lookup or initial-stock workbook','The model input is incomplete'],['Numerical method / adapters','A rerun may differ despite matching parameters'],['License and attribution','Reuse conditions and credit are unclear'],['Execution record','A figure cannot be traced to an observed run']]),fair='R',stage='archive')
reuse(46,'ro-crate','An RO-Crate packages a research object',cols(ul('Selected model and scenario inputs.','Runner, readers and numerical adapters.','Citation and license metadata.','Observed environment and execution record.','Actual results and file hashes.'),p('A JSON-LD manifest connects the files and their meaning. Preservation becomes easier when the evidence travels together.')+p('A crate is not a guarantee that every future machine can execute the research.')),fair='R1.2 · R2',stage='archive',sources=['https://www.researchobject.org/ro-crate/'])
divider(47,'practical3','Practical 3: package an actual run','Practical 3','R','archive')
add(48,'crate-exercise','Package the result you actually produced',code('from fair_hunter_prey import run_example, create_crate\n\nrun = run_example("stella", "case2", "out/crate-run")\ncrate = create_crate("out/crate-run", "out/research-object")\nprint(crate / "ro-crate-metadata.json")','Jupyter · examples/fair/03_ro_crate.ipynb')+ul('Inspect the JSON-LD manifest and execution/provenance.json.','Locate the selected configuration, original attribution and licenses.','Compare the recorded output checksum with the file in the crate.'),'Practical 3','R1.2 · R2','archive',notes='12 minutes. The exporter refuses changed inputs or outputs. It packages the selected case, not a vague model name.',sources=[BLOB+'examples/fair/03_ro_crate.ipynb'])
add(49,'crate-reflection','What travels with this result?',cols(ul('The source implementation and selected case.','The environment and observed execution.','The original authors and reuse conditions.'),p('What remains external? The literature, identifier infrastructure and any native vendor runtime. The crate should explain those dependencies rather than hide them.')),'Practical 3','R','archive')
add(50,'checklist','A FAIR4RS evidence checklist',table(['Area','Evidence to inspect'],[['Findable','Identifiers, versions, metadata, observed indexing'],['Accessible','Retrievable files, documented access, archival status'],['Interoperable','Formats, meanings, bindings, readers and tested translation'],['Reusable','Licenses, provenance, dependencies, tests and documentation']])+p('Use the '+file('docs/fair/evidence.md','repository evidence table')+' to distinguish implemented features from publication steps still pending.'),'Wrap-up','F · A · I · R','archive',notes='A completed checklist is an assessment aid, not a certification that every future reuse will work.')
add(51,'services','Services supporting the workflow',table(['Service','Role'],[['Betty Research Engine','Discovery and inspection of indexed metadata'],['Terminology Service / semantic model','Definitions, vocabulary references and file bindings'],['NFDI4Ing Jupyter','Open inspection and independent Python execution'],['RDMO','Software and data management planning'],['Coscine / ing.grid','Related storage and publication services from the lecture series']]),'Wrap-up',stage='archive',notes='Only claim interactions that participants actually performed. Terminology service concepts and local draft terms have different authority.',sources=['https://software.nfdi4ing.de/','https://terminology.nfdi4ing.de/','https://jupyter.nfdi4ing.de/','https://rdmo.nfdi4ing.de/','https://coscine.de/','https://ing.grid/'])
add(52,'discussion','Shared science. Traceable implementations.',p('Which artifact would a collaborator need first to reuse your model?')+p(link(SITE,'Explore the semantic model')+' · '+file('docs/fair/README.md','Run the examples')+' · '+file('docs/fair/evidence.md','Inspect the FAIR evidence'))+p('The native tools remain proprietary. The research becomes easier to find, inspect, and reproduce when its artifacts carry their context.'),'Wrap-up',stage='archive',kind='chapter-page',notes='Credits: original model by Mike Deaton and Rod MacDonald; repository implementations by Raphael Ginster, Matthias Papesch and Vasiliy Seibert; lecture adaptation by Vasiliy Seibert. See source manifest and REUSE mapping.',sources=[RDA,REPO])
for id,title,name,caption,source in [
 ('appendix-repository','Repository evidence','repository.jpg','The repository before this additive FAIR change.',REPO),
 ('appendix-binding','A value and its configuration binding','configuration-binding.jpg','The assignment, parameter and source file are distinct entities.',SITE+'#workflows/assignment%2Fcase2%2Ffraction-predators-killed-per-year'),
 ('appendix-file','The original Case 2 changes file','case2-file.jpg','Four changes, preserved exactly as the collaborators recorded them.',REPO+'/blob/f156dcf37597c0587958f463985986f0ea91accf/models/config/scenarios/case2.cin'),
 ('appendix-workflow','From configuration to an inspected figure','workflow.jpg','The existing semantic workflow labels native provenance as reconstructed.',SITE+'#workflows/diagram/case2-parameter-to-figure'),
 ('appendix-stella','Stella Architect: existing native evidence','stella-case2.jpg','Existing screenshot from the stella branch. No new native run is claimed.',REPO+'/blob/194a8b92e963920e95393accc7d5699348864d85/docs/kaibab_ecosystem_screenshot_stella_scenario2.jpg'),
 ('appendix-notebook','The existing inspection notebook','notebook.jpg','Saved outputs document inspection of existing CSVs, not a new simulation.',SITE+'notebooks/inspect_results.html')]:
    add(None,id,title,image(name,title,caption),'Optional appendix',stage='results',notes=caption,sources=[source])

STAGES = ['specification','implementation','configuration','execution','results','archive']
LABELS = ['Scientific specification','Vensim / Stella','Case configuration','Execution','Open inspection','FAIR record']

def render():
    sections=[]
    for i,s in enumerate(S,1):
        workflow='<ol class="workflow" aria-label="Research workflow">'+''.join('<li'+(' class="active" aria-current="step"' if stage==s['stage'] else '')+'>'+label+'</li>' for stage,label in zip(STAGES,LABELS))+'</ol>'
        sources=' · '.join(link(u,'Source '+str(j+1)) for j,u in enumerate(s['sources']))
        sections.append('<section id="'+s['id']+'" class="'+s['kind']+'" data-group="'+s['group']+'"><header><img src="assets/logos/nfdi4ing-logo.svg" alt="NFDI4Ing"><span>'+s['group']+'</span><span class="principle">'+s['fair']+'</span></header><h1>'+s['title']+'</h1><div class="slide-body">'+s['body']+'</div>'+workflow+'<footer><span>FAIR4RS · Hunter–prey</span><span>'+sources+'</span></footer><aside class="notes">'+E(s['notes'] or s['title']+'. Relate this point to the highlighted stage of the shared workflow.')+'<br>'+sources+'</aside></section>')
    html='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="FAIR4RS around a shared Kaibab model implemented in Vensim and Stella Architect"><title>FAIR4RS · Vensim, Stella and open research artifacts</title><link rel="stylesheet" href="vendor/reveal/dist/reset.css"><link rel="stylesheet" href="vendor/reveal/dist/reveal.css"><link rel="stylesheet" href="css/nfdi4ing-theme.css"><link rel="stylesheet" href="css/slides.css"><link rel="stylesheet" href="css/hunter-prey.css"></head><body><button id="agenda-toggle" aria-label="Open agenda (M)" aria-haspopup="dialog">☰</button><dialog id="lecture-agenda" aria-labelledby="agenda-title"><div class="agenda-head"><h2 id="agenda-title">Lecture agenda</h2><button id="agenda-close" aria-label="Close agenda">×</button></div><nav aria-label="Slides"></nav><p>M: agenda · Esc: close · O: overview · S: speaker notes</p></dialog><div class="reveal"><div class="slides">'''+''.join(sections)+'''</div></div><script src="vendor/reveal/dist/reveal.js"></script><script src="vendor/reveal/plugin/notes/notes.js"></script><script src="vendor/reveal/plugin/search/search.js"></script><script src="presentation.js"></script></body></html>'''
    (OUT/'index.html').write_text(html)
    outline=json.loads((OUT/'reference-outline.json').read_text())
    coverage=[{'original_slide':s['original'],'original_title':outline[s['original']-1]['title'],'adapted_id':s['id'],'adapted_slide':i,'adapted_title':s['title']} for i,s in enumerate(S,1) if s['original']]
    (OUT/'coverage.json').write_text(json.dumps(coverage,indent=2)+'\n')
    (OUT/'catalog.json').write_text(json.dumps([{k:v for k,v in s.items() if k!='body'} for s in S],indent=2)+'\n')
    print(f'{len(S)} slides; {len(coverage)} reference topics mapped')

if __name__=='__main__':render()
