#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Raphael Ginster
# SPDX-FileCopyrightText: 2026 Matthias Papesch
# SPDX-FileCopyrightText: 2026 Vasiliy Seibert
# SPDX-License-Identifier: MIT
#
# Smoke test for the Copier template: generate a project in both licensing
# variants and check that each one is REUSE-compliant.
#
# Needs uv (https://docs.astral.sh/uv/). Run from the repository root:
#   ./scripts/check_template.sh

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

copier() { uvx --from copier copier "$@"; }
reuse()  { uvx --from 'reuse[charset-normalizer]' reuse "$@"; }

cat > "$workdir/own-model.yml" <<'ANSWERS'
project_name: Smoke Test Own Model
project_slug: smoke-test-own-model
project_description: Generated by check_template.sh to verify the template.
authors:
  - family-names: Doe
    given-names: Jane
copyright_year: "2026"
model_slug: smoke_test
tools: [vensim, pysd]
code_license: MIT
third_party_model: false
include_ci: true
ANSWERS

cat > "$workdir/third-party.yml" <<'ANSWERS'
project_name: Smoke Test Third Party
project_slug: smoke-test-third-party
project_description: Generated by check_template.sh to verify the template.
authors:
  - family-names: Doe
    given-names: Jane
copyright_year: "2026"
model_slug: smoke_test
tools: [vensim, stella, pysd]
code_license: Apache-2.0
third_party_model: true
third_party_license: CC-BY-NC-SA-4.0
third_party_attribution: "Doe, J. (2024). A Model. Publisher."
include_ci: true
ANSWERS

status=0
for variant in own-model third-party; do
    target="$workdir/$variant"
    printf '\n=== %s ===\n' "$variant"

    copier copy --data-file "$workdir/$variant.yml" --defaults --quiet \
        "$repo_root" "$target"

    # reuse only honours .gitignore inside a git repository
    git -C "$target" init -q .
    git -C "$target" add -A

    if (cd "$target" && reuse lint --quiet); then
        echo "REUSE: compliant"
    else
        echo "REUSE: FAILED"
        (cd "$target" && reuse lint) || true
        status=1
    fi

    # Every directory the layout promises must exist after generation.
    for dir in models models/export models/config/lookups models/config/parameters \
               models/config/scenarios models/config/timeseries scripts tests \
               results/runs results/figures docs; do
        if [ ! -d "$target/$dir" ]; then
            echo "STRUCTURE: FAILED -- $dir was not generated"
            status=1
        fi
    done

    # Every generated directory must be tracked, or it vanishes on first clone.
    for dir in models models/config/parameters scripts tests docs results/runs; do
        if ! git -C "$target" ls-files --error-unmatch "$dir" >/dev/null 2>&1; then
            echo "STRUCTURE: FAILED -- $dir generated but not tracked"
            status=1
        fi
    done
    : > "$target/results/runs/probe.vdfx"
    if git -C "$target" check-ignore -q results/runs/probe.vdfx; then
        rm -f "$target/results/runs/probe.vdfx"
    else
        echo "STRUCTURE: FAILED -- *.vdfx is not ignored"
        rm -f "$target/results/runs/probe.vdfx"
        status=1
    fi

    [ "$status" -eq 0 ] && echo "structure: OK"
done

printf '\n'
if [ "$status" -eq 0 ]; then
    echo "template OK"
else
    echo "template BROKEN"
fi
exit "$status"
